- type: startingGear
  id: CourierGear
  subGear:
  - CourierPhoronmanGear
  equipment:
    head: ClothingHeadCourier
    jumpsuit: ClothingUniformCourier
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: CourierBag

- type: startingGear
  id: CourierPhoronmanGear
  parent: BasePhoronmanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCourier
    head: ClothingHeadEnvirohelmCourier
    gloves: ClothingHandsGlovesEnviroglovesCargo
