- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  requirements:
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
    - IPC
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hire
  access:
  - Chapel
  - Research
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser
    - type: Condemned

- type: startingGear
  id: ChaplainGear
  subGear:
  - ChaplainPhoronmanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitChaplain
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook

- type: startingGear
  id: ChaplainPhoronmanGear
  parent: BasePhoronmanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitChaplain
    head: ClothingHeadEnvirohelmChaplain
    gloves: ClothingHandsGlovesEnviroglovesBlack
