- type: job
  id: Librarian
  name: job-name-librarian
  description: job-description-librarian
  playTimeTracker: JobLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hire
  access:
  - Research
  - Maintenance
  - Library


- type: startingGear
  id: LibrarianGear
  subGear:
  - LibrarianPhoronmanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLibrarian
    back: ClothingBackpack
    shoes: ClothingShoesBootsLaceup
    outerClothing: ClothingOuterCoatRnd
    id: LibrarianPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
    pocket2: HandLabeler
  storage:
    back:
    - BookRandom

- type: startingGear
  id: LibrarianPhoronmanGear
  parent: BasePhoronmanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitAncientVoid
    head: ClothingHeadEnvirohelmAncientVoid
    gloves: ClothingHandsGlovesEnviroglovesPrototype
