- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Epistemics
    min: 3600
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - ZengHuPharmaceuticals
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  subGear:
  - ScientistPhoronmanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackScience
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatRnd
    id: SciencePDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook

- type: startingGear
  id: ScientistPhoronmanGear
  parent: BasePhoronmanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitScientist
    head: ClothingHeadEnvirohelmScientist
    gloves: ClothingHandsGlovesEnviroglovesWhite
